Repository pytorch/kineto, pull requests merged in 2021-06, with the labels that each got.

#266 remove dead code
  tb_plugin/torch_tb_profiler/profiler/event_parser.py
  tb_plugin/torch_tb_profiler/profiler/node.py
Labels: cla signed

#267 Fix min and max column reverted bug
  tb_plugin/torch_tb_profiler/profiler/run_generator.py
Labels: cla signed, plugin

#215 Add multiple span route support
  tb_plugin/fe/src/api/README.md
  tb_plugin/fe/src/api/generated/api.ts
  tb_plugin/fe/src/api/openapi.yaml
  tb_plugin/fe/src/app.tsx
  tb_plugin/fe/src/components/DistributedView.tsx
  tb_plugin/fe/src/components/FullCircularProgress.tsx
  tb_plugin/fe/src/components/GpuInfoTable.tsx
  tb_plugin/fe/src/components/Kernel.tsx
  tb_plugin/fe/src/components/MemoryView.tsx
  tb_plugin/fe/src/components/Operator.tsx
  tb_plugin/fe/src/components/Overview.tsx
  tb_plugin/fe/src/components/TextListItem.tsx
  tb_plugin/fe/src/components/TraceView.tsx
  tb_plugin/fe/src/components/helpers.tsx
  tb_plugin/fe/src/components/tables/CallStackTable.tsx
  tb_plugin/fe/src/components/tables/OperationTable.tsx
  tb_plugin/test/test_compare_with_autograd.py
  tb_plugin/test/test_profiler.py
  tb_plugin/test/test_tensorboard_end2end.py
  tb_plugin/torch_tb_profiler/consts.py
  tb_plugin/torch_tb_profiler/plugin.py
  tb_plugin/torch_tb_profiler/profiler/data.py
  tb_plugin/torch_tb_profiler/profiler/event_parser.py
  tb_plugin/torch_tb_profiler/profiler/loader.py
  tb_plugin/torch_tb_profiler/profiler/module_parser.py
  tb_plugin/torch_tb_profiler/profiler/run_generator.py
  tb_plugin/torch_tb_profiler/run.py
  tb_plugin/torch_tb_profiler/static/index.html
Labels: cla signed

#272 add span check before calling backend api
  tb_plugin/fe/src/app.tsx
  tb_plugin/torch_tb_profiler/static/index.html
Labels: cla signed

#274 bump version
  tb_plugin/torch_tb_profiler/__init__.py
  tb_plugin/torch_tb_profiler/consts.py
Labels: cla signed

#273 Add communication recommendation for tb_plugin
  tb_plugin/torch_tb_profiler/profiler/data.py
  tb_plugin/torch_tb_profiler/profiler/event_parser.py
Labels: cla signed

#275 fix typo
  tb_plugin/torch_tb_profiler/profiler/run_generator.py
Labels: cla signed

#277 fix typo and add recommendation note
  tb_plugin/torch_tb_profiler/profiler/data.py
  tb_plugin/torch_tb_profiler/profiler/run_generator.py
Labels: cla signed

#279 update tb_plugin Readme
  tb_plugin/README.md
  tb_plugin/docs/gpu_utilization.md
  tb_plugin/docs/images/control_panel.PNG
  tb_plugin/docs/images/distributed_view.PNG
  tb_plugin/docs/images/kernel_view.PNG
  tb_plugin/docs/images/memory_view.PNG
  tb_plugin/docs/images/operator_view.PNG
  tb_plugin/docs/images/overall_view.PNG
  tb_plugin/docs/images/trace_view.PNG
  tb_plugin/docs/images/trace_view_gpu_utilization.PNG
  tb_plugin/docs/images/trace_view_launch.PNG
  tb_plugin/docs/images/trace_view_one_step.PNG
  tb_plugin/docs/images/vscode_stack.PNG
  tb_plugin/examples/resnet50_profiler_api.py
  tb_plugin/samples/resnet50_num_workers_0/worker0.1623143089861.pt.trace.json.gz
  tb_plugin/samples/resnet50_num_workers_0/worker0.1623143566756.pt.trace.json.gz
  tb_plugin/samples/resnet50_num_workers_0/worker0.pt.trace.json.gz
  tb_plugin/samples/resnet50_num_workers_4/worker0.1623212756351.pt.trace.json.gz
  tb_plugin/samples/resnet50_num_workers_4/worker0.1623213129365.pt.trace.json.gz
  tb_plugin/samples/resnet50_num_workers_4/worker0.pt.trace.json.gz
  tb_plugin/test/result_check_file.txt
  tb_plugin/test/test_tensorboard_end2end.py
Labels: cla signed

#285 update tb_plugin README
  tb_plugin/README.md
Labels: cla signed

#290 Fix bug in pagination being unchangeable
  tb_plugin/fe/src/components/charts/AntTableChart.tsx
  tb_plugin/fe/src/components/tables/MemoryTable.tsx
  tb_plugin/fe/src/components/tables/OperationTable.tsx
  tb_plugin/torch_tb_profiler/static/index.html
Labels: cla signed

#289 Update tooltip of GPU metrics
  tb_plugin/test/result_check_file.txt
  tb_plugin/torch_tb_profiler/consts.py
  tb_plugin/torch_tb_profiler/profiler/run_generator.py
  tb_plugin/torch_tb_profiler/run.py
Labels: cla signed

#287 fix typo
  tb_plugin/README.md
Labels: cla signed, documentation, plugin

#288 Update README.md
  tb_plugin/README.md
Labels: cla signed, documentation, plugin

#298 remove the Record Window End event
  tb_plugin/torch_tb_profiler/profiler/data.py
Labels: cla signed

#303 Refine document and tooltips
  tb_plugin/README.md
  tb_plugin/test/result_check_file.txt
  tb_plugin/torch_tb_profiler/consts.py
  tb_plugin/torch_tb_profiler/profiler/run_generator.py
  tb_plugin/torch_tb_profiler/run.py
Labels: cla signed

#305 fix bug of kernel out of step
  tb_plugin/test/test_profiler.py
  tb_plugin/torch_tb_profiler/profiler/gpu_metrics_parser.py
  tb_plugin/torch_tb_profiler/profiler/run_generator.py
  tb_plugin/torch_tb_profiler/run.py
Labels: cla signed

#306 Update readme
  tb_plugin/docs/gpu_utilization.md
  tb_plugin/test/result_check_file.txt
  tb_plugin/torch_tb_profiler/consts.py
Labels: cla signed

#307 rename error word spelling
  tb_plugin/test/test_profiler.py
  tb_plugin/torch_tb_profiler/profiler/data.py
  tb_plugin/torch_tb_profiler/profiler/gpu_metrics_parser.py
  tb_plugin/torch_tb_profiler/profiler/run_generator.py
  tb_plugin/torch_tb_profiler/run.py
Labels: cla signed

#312 fix typo in readme
  tb_plugin/README.md
Labels: cla signed

#315 add notes of python version in case of circular import bug
  tb_plugin/README.md
Labels: cla signed

#316 Workaround: update example to speedup
  tb_plugin/examples/resnet50_profiler_api.py
Labels: cla signed, plugin

#323 Fix bugs happens with tensorboard 1.15
  tb_plugin/torch_tb_profiler/plugin.py
Labels: cla signed

#330 workaround for negative gpu metrics from input json file
  tb_plugin/torch_tb_profiler/profiler/gpu_metrics_parser.py
Labels: cla signed
